title: Cambridge Colllection
description: Scrapped Data Related to the city of Cambridge, Ontario.
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
