# This GitHub Action runs in each pull-requests.
# It tests building of the static Jekyll site.

name: Pull-request - Build static site

on:
  pull_request:

jobs:

  build_static_jekyll_site:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Ruby environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems

      - name: Build the Jekyll static site
        run: bundle exec jekyll build
